// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC99y0YqyX7OJ-vCXAny-NdEkoKjwfrV0Q',
    appId: '1:1005987793010:web:f56f04cd742e5997d51aeb',
    messagingSenderId: '1005987793010',
    projectId: 'learnock-471408',
    authDomain: 'learnock-471408.firebaseapp.com',
    storageBucket: 'learnock-471408.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_G6ZTnAWg-DWPPaBRF5Dc_CazexEftA',
    appId: '1:1005987793010:android:4da8067b89132c96d51aeb',
    messagingSenderId: '1005987793010',
    projectId: 'learnock-471408',
    storageBucket: 'learnock-471408.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZUp9GBumSpymsxZB6hf3zU75D_xRbu0Y',
    appId: '1:1005987793010:ios:c057c02338b02f6ad51aeb',
    messagingSenderId: '1005987793010',
    projectId: 'learnock-471408',
    storageBucket: 'learnock-471408.firebasestorage.app',
    androidClientId: '1005987793010-422dlt9oasqcagrsl0vhtepimf4s54o0.apps.googleusercontent.com',
    iosClientId: '1005987793010-veikjvm9u7g1lgql7kevpv13bggjku6c.apps.googleusercontent.com',
    iosBundleId: 'com.elprof.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZUp9GBumSpymsxZB6hf3zU75D_xRbu0Y',
    appId: '1:1005987793010:ios:c057c02338b02f6ad51aeb',
    messagingSenderId: '1005987793010',
    projectId: 'learnock-471408',
    storageBucket: 'learnock-471408.firebasestorage.app',
    androidClientId: '1005987793010-422dlt9oasqcagrsl0vhtepimf4s54o0.apps.googleusercontent.com',
    iosClientId: '1005987793010-veikjvm9u7g1lgql7kevpv13bggjku6c.apps.googleusercontent.com',
    iosBundleId: 'com.elprof.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSoKmcNAqrpVRyX0twQGmjBSdR4vgPtMY',
    appId: '1:1005987793010:web:333cf64c3b256904d51aeb',
    messagingSenderId: '1005987793010',
    projectId: 'learnock-471408',
    authDomain: 'learnock-471408.firebaseapp.com',
    storageBucket: 'learnock-471408.firebasestorage.app',
  );
}
