// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg9Vnu7vVi0DddX-UTUGK_rG-dXv6LWiE',
    appId: '1:406946183197:web:a65862f26d0996ab3f6ef4',
    messagingSenderId: '406946183197',
    projectId: 'aerial-sandbox-508613-d5',
    authDomain: 'aerial-sandbox-508613-d5.firebaseapp.com',
    storageBucket: 'aerial-sandbox-508613-d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZpCkTYW3zrD9X4f0G-QFFGwvZUnpJCQ',
    appId: '1:406946183197:android:4954a9c3a734793b3f6ef4',
    messagingSenderId: '406946183197',
    projectId: 'aerial-sandbox-508613-d5',
    storageBucket: 'aerial-sandbox-508613-d5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0kIdMM3gpVcpgnITHUc82yAjno8_bbGs',
    appId: '1:406946183197:ios:a0ff02820350fb603f6ef4',
    messagingSenderId: '406946183197',
    projectId: 'aerial-sandbox-508613-d5',
    storageBucket: 'aerial-sandbox-508613-d5.firebasestorage.app',
    iosClientId: '406946183197-sckuo715n49oo8h66uf52cdurl6uscib.apps.googleusercontent.com',
    iosBundleId: 'com.pioneeracademy.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0kIdMM3gpVcpgnITHUc82yAjno8_bbGs',
    appId: '1:406946183197:ios:a0ff02820350fb603f6ef4',
    messagingSenderId: '406946183197',
    projectId: 'aerial-sandbox-508613-d5',
    storageBucket: 'aerial-sandbox-508613-d5.firebasestorage.app',
    iosClientId: '406946183197-sckuo715n49oo8h66uf52cdurl6uscib.apps.googleusercontent.com',
    iosBundleId: 'com.pioneeracademy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg9Vnu7vVi0DddX-UTUGK_rG-dXv6LWiE',
    appId: '1:406946183197:web:dea5a896d5c333bb3f6ef4',
    messagingSenderId: '406946183197',
    projectId: 'aerial-sandbox-508613-d5',
    authDomain: 'aerial-sandbox-508613-d5.firebaseapp.com',
    storageBucket: 'aerial-sandbox-508613-d5.firebasestorage.app',
  );
}
